- platform: synologydsm
  name: nasmonitor
  host: !secret synology_ip
  username: !secret synology_user
  password: !secret synology_password
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - network_up
    - network_down
    - disk_name
    - disk_status
    - disk_temp
